module.exports = [{
  uid: 17,
  name: 'ROULEAUX DE PRINTEMPS LÉGUMES-RIZ',
  description: 'Recette facile, Pour 4 Personnes',
  prepTime: 45,
  cookTime: 20,
  steps: ['LÉGUMES-RIZ Faites bouillir le riz dans une grande quantité d’eau jusqu’à cuisson. Epluchez la carotte et coupez-la en petits cubes ; faites la même chose avec l’oignon et le poivron. Coupez l’échalote en rondelles. Ramollissez les légumes dans une grande quantité d’eau chaude puis plongez-les dans l’eau glacée. Emincez la ciboulette et la coriandre. Mélangez bien le riz les légumes et les herbes dans un bol.  Séparez les blancs d’oeufs des jaunes et ajoutez ces derniers au mélange de légumes. Mettez les blancs de côté pour une utilisation ultérieure. Assaisonnez à votre goût avec le piment en poudre et le poivre. ROULEAUX DE PRINTEMPSVous pouvez acheter des pâtes à rouleaux de printemps toutes faites au supermarché ou en épicerie asiatique. Déballez et placez deux morceaux déroulés de wrappers l’un sur l’autre pour le remplissage. Lorsque vous avez  empilé toutes les pâtes et mises côte à côte, posez une quantité égale de garniture légumes-riz sur chaque pile. Etalez au pinceau du blanc d’oeuf sur les bords de la pâte, repliez les extrémités et roulez chaque pile étroitement pour former les rouleaux de printemps. Couvrez une plaque de cuisson avec du papier sulfuris et placez les rouleaux de printemps dessus. Badigeonnez chaque rouleau avec un peu de crème liquide. Cuisez au four à 200°C pendant 15-20 min jusqu’à ce qu’ils soient légèrement dorés. Sortez les rouleaux de printemps du four, coupez-les en  diagonal et placez-les sur les épinards, qui auront été préalablement décongelés et cuits sans aucun liquide'],
  ingredients:
  {
    riz: 100,
    carrotte: 1,
    'oignon rouge': 1,
    poivron: 1,
    echalote: 1,
    'petite botte de ciboulette': 1,
    'botte de coriandre': 0.5,
    oeuf: 2,
    'cuillière à café de piment': 0.5,
    'pätes doubles à rouleaux de printemps': 8,
    'cuillère à soupe de crême': 2,
    "paquet d'epinards surgelès": 1,
  },
},
{
  uid: 17,
  name: 'Boules d’énergie sans cuisson',
  description: 'Recette facile, Pour 8 Personnes',
  prepTime: 10,
  cookTime: 0,
  steps: [
    'Mettre le beurre d’arachide, le miel et la vanille dans un bol à mélanger. Cuire 30 secondes au four à micro-ondes.',
    'Ajouter les graines de lin moulues et les céréales.',
    'Mélanger jusqu’à ce que le tout soit homogène.',
    'Mettre le mélange au congélateur pendant 10 minutes.',
    'Façonner 16 boules d’énergie.',
    'Ranger les boules dans un contenant hermétique, couvrir et réfrigérer.',
  ],
  ingredients:
    {
      'tasse de beurre d’arachide naturel': 0.5,
      'tasse de miel liquide': 0.5,
      'c. à thé de vanille': 1,
      'tasse de graines de lin moulues': 0.25,
      'tasses de céréales de riz soufflé': 2,
    },
},
{
  uid: 17,
  name: 'Bouddha bowl à l’orge',
  description: 'Recette facile, Pour 4 Personnes',
  prepTime: 10,
  cookTime: 0,
  steps: [
    'Préchauffer le four à 400 °F. Arroser le brocoli d’huile d’olive, mélanger et répartir le tout sur une tôle à biscuits. Cuire pendant 20 minutes. Réserver.',
    'Mettre les œufs dans une casserole et les couvrir d’eau froide. Amener à ébullition. Couvrir la casserole et la retirer du feu. Laisser reposer les œufs pendant 10 à 12 minutes, puis les rincer à l’eau froide. Retirer la coquille et couper les œufs en deux. Réfrigérer.',
    'Faire cuire l’orge en suivant les instructions sur l’emballage. Égoutter et laisser refroidir.',
    'Assembler les bols du bouddha un par un, comme suit :¼ de l’orge1 tasse de roquette¼ des fleurettes de brocoli2 œufs durs (4 moitiés)1 c. à soupe de carottes râpées',
    'Arroser chaque bol de 1 c. à soupe d’huile d’olive et de 1 c. à soupe de jus de citron. Servir immédiatement',
  ],
  ingredients:
    {
      'tête de brocoli (400 mL),  en fleurettes de 1 po': 1,
      'gros œufs': 8,
      'tasse d’orge non cuite': 0.66,
      'c. à soupe de carottes râpées': 4,
      'tasses de bébé roquette': 4,
      'c. à soupe d’huile d’olive': 4,
      'c. à soupe de jus de citron': 4,
    },
},
];
